### ISSUE TITLE
need to test BFCACF probs with scale factor q > 1

### ISSUE THREAD

**Issue by newexo** [garden-of-delete/recombo_public#15]
Check that results match literature

**Comment by newexo** [comment]
Wait a minute, @garden-of-delete . Please look at src/tests/clkTests.cpp lines 718-728. These seem to be for q=3.

Is the task to check that these match literature?

**Comment by newexo** [comment]
Unfortunately, it does not appear that I have access to "Monte Carlo Study of Polymer Systems by Multiple Markov Chain Method" by Enzo Orlandini. Was there another which might have contained computed examples?

**Comment by newexo** [comment]
Okay. I have Schmirler's thesis. I will compute by hand probabilities for two z-values and two q-values using equations 4.7 on page and write a test that checks against those hand computed probabilities.

https://central.bac-lac.gc.ca/.item?id=TC-SSU-201209670&op=pdf&app=Library&oclc_number=1032987533

**Comment by garden-of-delete** [comment]
We have confirmed that the bfacf probability for P(-2) being computed in the probmap for q > 1. The test here:
```
bool testPrecomputedBfacf3Probs(){
	clkCigar square;
	clkConformationAsList square1(square);
	testClkConformationBfacf3 knot(square1);
	//select a z with q=1
	double z = .2000, q = 1;
	//precompute probabilities
	knot.init_Q(z, q);
	//compare precomputed probabilities with directly computed probabilities
	for (int n = 4; n < MAX_PRECOMPUTE_LENGTH; n++){
		ASSERT(knot.probMap[n].p_plus2 == (pow((n + 2), (q - 1))*(z * z)) / (pow(n, (q - 1)) + 3.0*pow((n + 2), q - 1) * z * z));
		ASSERT(knot.probMap[n].p_minus2 == pow(n, (q - 1)) / (pow(n, (q - 1)) + 3.0*pow((n + 2), q - 1) * z * z));
		ASSERT(knot.probMap[n].p_0 == .5*((pow((n + 2), (q - 1))*(z * z)) / (pow(n, (q - 1)) + 3.0*pow((n + 2), q - 1) * z * z) +
			pow(n, (q - 1)) / (pow(n, (q - 1)) + 3.0*pow((n + 2), q - 1) * z * z)));
	}
	//select a different z with q=3
	z = .1812; q = 3;
	//precompute
	knot.init_Q(z, q);
	//compare
	for (int n = 4; n < MAX_PRECOMPUTE_LENGTH; n++){
		ASSERT(knot.probMap[n].p_plus2 == (pow((n + 2), (q - 1))*(z * z)) / (pow(n, (q - 1)) + 3.0*pow((n + 2), q - 1) * z * z));
		ASSERT(knot.probMap[n].p_minus2 == pow(n, (q - 1)) / (pow(n, (q - 1)) + 3.0*pow((n + 2), q - 1) * z * z));
		ASSERT(knot.probMap[n].p_0 == .5*((pow((n + 2), (q - 1))*(z * z)) / (pow(n, (q - 1)) + 3.0*pow((n + 2), q - 1) * z * z) +
			pow(n, (q - 1)) / (pow(n, (q - 1)) + 3.0*pow((n + 2), q - 1) * z * z)));
	}
	
	return true;
}
```
failed to catch the issue because the expression it is comparing the probmap to is also wrong. 

Steps to resolve this issue:
1. Fix the broken test
2. Find and fix the expression that is miscomputing these probabilities in the probMap
3. Verify the test passes
