### ISSUE TITLE
homfly not building with clang

### ISSUE THREAD

**Issue by newexo** [garden-of-delete/recombo_public#17]
I really thought I had tried this within the last year. Must have been longer, though.

```
$ make homfly 
depbase=`echo src/cross.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT src/cross.o -MD -MP -MF $depbase.Tpo -c -o src/cross.o src/cross.c &&\
	mv -f $depbase.Tpo $depbase.Po
src/cross.c:525:7: error: implicitly declaring library function 'strlen' with type 'unsigned long (const char *)' [-Werror,-Wimplicit-function-declaration]
  l = strlen(chaine);
      ^
src/cross.c:525:7: note: include the header <string.h> or explicitly provide a declaration for 'strlen'
src/cross.c:540:43: warning: too few arguments in call to 'creerCroisement'
      if((debut = creerCroisement(DEBUT,-1))==NULL){
                  ~~~~~~~~~~~~~~~         ^
src/cross.c:722:43: warning: too few arguments in call to 'creerCroisement'
      if((debut = creerCroisement(DEBUT,-1))==NULL){
                  ~~~~~~~~~~~~~~~         ^
2 warnings and 1 error generated.
make: *** [src/cross.o] Error 1

```

Apple clang version 13.0.0 (clang-1300.0.29.3)

**Comment by Metrodorus** [comment]
Hi.   

The homfly code uses very loose K&R style C.   I think you may have to turn down the strictness of your compilation.

I've recently packaged up ghomfly (what I call this version) and jhomfly (Jenkins' version) together with their corresponding gidknot and jidknot and have done extensive testing.  jhomfly greatly out-performs ghomfly and in most cases I would suggest that ghomfly be retired. 

We can chat about this sometime.

**Comment by newexo** [comment]
@Metrodorus indeed, this code for computing HOMFLY is very old. The recombo_public project will probably have to remain as close to stand-alone as possible, so I will try to get this working. Is source code available for jhomfly?

I see a suggestion related to similar problems compiling C and Objective C related to implicit function calls on Mac. It seems that implicit function declarations were deprecated as of C99, but remained warnings until Xcode 12.

https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes

"Clang now reports an error when you use a function without an explicit declaration when building C or Objective-C code for macOS (-Werror=implicit-function-declaration flag is on)."

**Comment by newexo** [comment]
https://github.com/garden-of-delete/recombo_public/pull/19

**Comment by garden-of-delete** [comment]
Addressed in PR, closing issue.
