### ISSUE TITLE
Old Makefiles

### ISSUE THREAD

**Issue by newexo** [garden-of-delete/recombo_public#7]
After I got the autotool build working, I have not removed the old Makefiles from the src directories. Do we intend to keep those? If so, we currently have no description in the readme file.

**Comment by garden-of-delete** [comment]
I say if the binaries are now building with automake, no need to keep old makefiles around.

**Comment by newexo** [comment]
Cool. I will make a PR.

**Comment by newexo** [comment]
This addressed.
