### ISSUE TITLE
What are the bugs in clkConformationBfacf3::impl::searchForRecomboSitesOneComp(int minarclength, int maxarclength)?

### ISSUE THREAD

**Issue by newexo** [garden-of-delete/recombo_public#9]
There is a comment claiming that searchForRecomboSitesOneComp(int minarclength, int maxarclength) is used only in runRecombo and that there are bugs. Unfortunately, the comment does not elaborate. Is this function any longer needed, or is it safe to delete?

**Comment by newexo** [comment]
I think we will never know what were the bugs. This PR deletes the questionable function: https://github.com/garden-of-delete/recombo_public/pull/22

**Comment by garden-of-delete** [comment]
No longer relevant, closing issue.
